spring:
  application:
    name: reminder

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/reminder_db
    username: postgres
    password: postgres

  mvc:
    hiddenmethod:
      filter:
        enabled: true
#server:
#  tomcat:
#    relaxed-path-chars: \
#    relaxed-query-chars: \